[deps]
CacheAwareConv = "ae0c0968-3b55-4cf5-aa46-61dd257e9e80"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[sources]
CacheAwareConv = {path = "/home/runner/work/CacheAwareConv.jl/CacheAwareConv.jl"}

[compat]
CacheAwareConv = "1"
Documenter = "1"
